newIssueWelcomeComment: >
  Thanks for opening your issue here! Be sure to follow the issue template!

newPRWelcomeComment: >
  Thanks for opening this pull request! Please check out our contributing guidelines
  
firstPRMergeComment: >
  Congrats on merging your first pull request! We are proud of you and grateful for all the hardworks!
